import { StyleSheet } from "react-native";

export const ButtonStyles = StyleSheet.create({
  primary: {
    backgroundColor: "#800080",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
  },
  warning: {
    backgroundColor: "#ff4444",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
  },
  secondary: {
    backgroundColor: "#ccc",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
  },
  text: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },

  // Alert / Success specific styles
  alertOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  alertBox: {
    backgroundColor: '#fff',
    borderRadius: 15,
    width: '80%',
    height: '20%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    overflow: 'hidden',
    paddingTop: 15,
    paddingBottom: 15,
  },
  alertIcon: {
    marginBottom: 5,
    marginLeft: 'auto',
    marginRight: 'auto',
    width: 50,
    height: 50,
  },
  alertMessage: {
    color: '#333',
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 2,
    lineHeight: 15,
    paddingHorizontal: 25,
  },
  alertButton: {
    backgroundColor: '#800080',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 17,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  alertButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
